// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/jams.tsx";
import * as $4 from "./routes/winners.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
    routes: {
        "./routes/[name].tsx": $0,
        "./routes/_app.tsx": $1,
        "./routes/index.tsx": $2,
        "./routes/jams.tsx": $3,
        "./routes/winners.tsx": $4,
    },
    islands: {
        "./islands/Counter.tsx": $$0,
    },
    baseUrl: import.meta.url,
    config,
};

export default manifest;
